(declare-fun x1 () Int)
(declare-fun x2 () Int)
(declare-fun x3 () Int)
(declare-fun y1 () Int)
(declare-fun y2 () Int)
(declare-fun y3 () Int)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun f (Int) Int)
(declare-fun g (Int) Int)

(assert (and (= (+ (f x1) x2) x3) (= (+ (f y1) y2) y3) (<= y1 x1)))
(assert (and (= x2 (g b)) (= y2 (g b)) (<= x1 y1) (< x3 y3)))
(check-sat)
